# Generated by Django 3.1.6 on 2021-02-07 10:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0002_auto_20210207_1520'),
    ]

    operations = [
        migrations.CreateModel(
            name='Psychologist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, null=True)),
                ('contact_number', models.CharField(max_length=13)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], default='Male', max_length=10)),
                ('age', models.SmallIntegerField(null=True)),
                ('phone', models.CharField(max_length=100, null=True)),
                ('email', models.CharField(max_length=100)),
                ('date_created', models.DateField(auto_now_add=True)),
                ('cnic', models.CharField(max_length=100)),
                ('session_fee', models.IntegerField(choices=[('500', '500'), ('1000', '1000'), ('2000', '2000'), ('3000', '3000'), ('4000', '4000'), ('4000', '4000'), ('6000', '6000'), ('7000', '7000'), ('8000', '8000'), ('9000', '9000'), ('10000', '10000')])),
                ('specialization', models.IntegerField(choices=[('CLINICAL PSYCHOLOGY', 'CLINICAL PSYCHOLOGY'), ('COUNSELING PSYCHOLOGY', 'COUNSELING PSYCHOLOGY'), ('DEVELOPMENTAL PSYCHOLOGY', 'DEVELOPMENTAL PSYCHOLOGY'), ('EDUCATIONAL PSYCHOLOGY', 'EDUCATIONAL PSYCHOLOGY'), ('EVIRONMENTAL PSYCHOLOGY', 'EVIRONMENTAL PSYCHOLOGY'), ('EXPERIMENTAL PSYCHOLOGY', 'EXPERIMENTAL PSYCHOLOGY'), ('FORENSIC PSYCHOLOGY', 'FORENSIC PSYCHOLOGY'), ('HUMAN FACTORS PSYCHOLOGY', 'HUMAN FACTORS PSYCHOLOGY'), ('SCHOOL PSYCHOLOGY', 'SCHOOL PSYCHOLOGY'), ('SOCIAL PSYCHOLOGY', 'SOCIAL PSYCHOLOGY'), ('SPORT PSYCHOLOGY', 'SPORT PSYCHOLOGY')])),
                ('degree', models.IntegerField(choices=[('BS PSYCHOLOGY', 'BS PSYCHOLOGY'), ('MS PSYCHOLOGY', 'MS PSYCHOLOGY'), ('PHD PSYCHOLOGY', 'PHD PSYCHOLOGY')])),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='paitent',
            name='name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.CreateModel(
            name='UserStory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('star', models.IntegerField()),
                ('comment', models.TextField(default='.', max_length=1500)),
                ('paitent_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.paitent')),
                ('psychologist_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.psychologist')),
            ],
        ),
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=2000)),
                ('psychologist_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.psychologist')),
            ],
        ),
    ]
