# Generated by Django 3.1.6 on 2021-02-07 12:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20210207_1647'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='psychologist_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.psychologist'),
        ),
        migrations.AlterField(
            model_name='userstory',
            name='paitent_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.paitent'),
        ),
        migrations.AlterField(
            model_name='userstory',
            name='psychologist_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.psychologist'),
        ),
    ]
