# Generated by Django 3.1.6 on 2021-02-14 07:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0007_remove_paitent_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userstory',
            name='paitent_id',
        ),
        migrations.RemoveField(
            model_name='userstory',
            name='psychologist_id',
        ),
        migrations.AlterField(
            model_name='blog',
            name='psychologist_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
