# Generated by Django 3.1.6 on 2021-02-14 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_auto_20210214_2318'),
    ]

    operations = [
        migrations.AddField(
            model_name='psychologist',
            name='bio',
            field=models.TextField(default='.', max_length=200),
        ),
    ]
