# Generated by Django 3.1.6 on 2021-03-30 17:00

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0010_psychologist_bio'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Paitent',
            new_name='Patient',
        ),
    ]
