# Generated by Django 3.1.6 on 2021-04-03 15:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0012_appointment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='psychologist',
        ),
        migrations.AddField(
            model_name='appointment',
            name='paitent_id',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='creator1', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='appointment',
            name='psychologist_id',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assignee1', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='time',
            field=models.DateTimeField(max_length=100),
        ),
    ]
