# Generated by Django 3.1.6 on 2021-04-03 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_auto_20210403_2004'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointment',
            old_name='paitent_id',
            new_name='paitent',
        ),
        migrations.RenameField(
            model_name='appointment',
            old_name='psychologist_id',
            new_name='psychologist',
        ),
    ]
