# Generated by Django 3.1.6 on 2021-04-04 11:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_auto_20210404_1233'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='approved',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='Charge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.CharField(max_length=100)),
                ('currency', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=500)),
                ('appointment', models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.appointment')),
            ],
        ),
    ]
